import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
export default function Home() {
  const { data: session, status } = useSession();

  const onClickHandler = async () => {
    await signIn("google");
  };

  const onSignOutHandler = async () => {
    await signOut({ redirect: false });
  };

  return (
    <div className="h-screen w-screen flex flex-col items-center text-center">
      <Head>
        <title>Sample NextAuth Freelancer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="w-full items-end flex flex-row">
        <div className="flex-grow"></div>
        <div className="p-5">
          <a href="#">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="40"
              height="40"
              viewBox="0 0 24 24"
            >
              <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm2.218 18.616c-.354.069-.468-.149-.468-.336v-1.921c0-.653-.229-1.079-.481-1.296 1.56-.173 3.198-.765 3.198-3.454 0-.765-.273-1.389-.721-1.879.072-.177.312-.889-.069-1.853 0 0-.587-.188-1.923.717-.561-.154-1.159-.231-1.754-.234-.595.003-1.193.08-1.753.235-1.337-.905-1.925-.717-1.925-.717-.379.964-.14 1.676-.067 1.852-.448.49-.722 1.114-.722 1.879 0 2.682 1.634 3.282 3.189 3.459-.2.175-.381.483-.444.936-.4.179-1.413.488-2.037-.582 0 0-.37-.672-1.073-.722 0 0-.683-.009-.048.426 0 0 .46.215.777 1.024 0 0 .405 1.25 2.353.826v1.303c0 .185-.113.402-.462.337-2.782-.925-4.788-3.549-4.788-6.641 0-3.867 3.135-7 7-7s7 3.133 7 7c0 3.091-2.003 5.715-4.782 6.641z" />
            </svg>
          </a>
        </div>
      </nav>
      <main className="flex flex-col space-y-5 flex-grow m-5">
        <h1>Next auth sample</h1>
        {status === "authenticated" ? (
          <span>
            <p>Signed in as {session.user?.email} ☑️</p>
            <button onClick={() => onSignOutHandler()}>Sign out</button>
          </span>
        ) : (
          <button
            onClick={() => onClickHandler()}
            className="p-3 text-lg bg-gray-200 rounded flex space-x-5 justify-center"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
            >
              <path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2.5 11.5v1.2h1.985c-.08.514-.601 1.51-1.985 1.51-1.194 0-2.17-.99-2.17-2.21s.976-2.21 2.17-2.21c.681 0 1.135.29 1.396.541l.949-.916c-.61-.57-1.401-.915-2.345-.915-1.936 0-3.5 1.565-3.5 3.5s1.564 3.5 3.5 3.5c2.02 0 3.359-1.419 3.359-3.419 0-.23-.024-.405-.055-.58h-3.304zm0 0 8.5 1h-1.5v1.5h-1v-1.5h-1.5v-1h1.5v-1.5h1v1.5h1.5v1z" />
            </svg>
            <span>Sign in with google</span>
          </button>
        )}
      </main>

      <footer className="m-5 my-10">
        Made by{" "}
        <a className="hover:underline" href="https://100lvlmaster.in">
          100lvlmaster
        </a>{" "}
        with ❤️.
      </footer>
    </div>
  );
}
